ALTER TABLE COMPLAINT ADD CONSTRAINT PK_COMPLAINT
PRIMARY KEY (COM_ID);
ALTER TABLE COMPLAINT ADD CONSTRAINT FK_COMPLAINT
FOREIGN KEY (BOARD_ID) REFERENCES BOARD(BOARD_ID);

--select clause
SELECT DISTINCT (CUST_ID+0),C_NAME,ADDRESS
FROM CUSTOMERS
WHERE ADDRESS like '%Dha%' AND CUST_ID BETWEEN 1 AND 10;
--set
SELECT DISTINCT (CUST_ID+0),C_NAME,ADDRESS
FROM CUSTOMERS
WHERE CUST_ID NOT IN(1,10);

--order by
SELECT CUST_ID
FROM CUSTOMERS
ORDER BY CUST_ID desc;