--lab 4 operations
--order by more than one column
SELECT CUST_ID,BILL_ID
FROM BILL
ORDER BY CUST_ID,BILL_ID desc;

--5 aggregate functions
--max
SELECT MAX(AMOUNT) FROM BILL;
--MIN
SELECT MIN(AMOUNT) FROM BILL;
--count function
SELECT COUNT(*), COUNT(COM_ID) FROM COMPLAINT;
SELECT COUNT(BOARD_ID), COUNT(DISTINCT BOARD_ID), COUNT(ALL BOARD_ID) FROM COMPLAINT;
--SUM AND AVERAGE
SELECT SUM(BOARD_ID), AVG(BOARD_ID), AVG(NVL(BOARD_ID,0))
FROM COMPLAINT;

--GROUP BY CLAUSE
SELECT BOARD_ID, COUNT(COM_ID)
FROM COMPLAINT
GROUP BY BOARD_ID;

--HAVING CLAUSE
SELECT BOARD_ID, COUNT(COM_ID)
FROM COMPLAINT
GROUP BY BOARD_ID
HAVING COUNT(COM_ID)>2;