--lab 5 operations
--subquery search
SELECT CUST_ID, C_NAME 
FROM CUSTOMERS
WHERE CUST_ID IN ( SELECT CUST_ID 
FROM BILL 
WHERE STAT= 'PAID');

--inserting using subquery
--creating a TEMPTABLEorary table to show demonstrate this operation
CREATE TABLE TEMPTABLE(
  TEMPTABLE_NAME VARCHAR(40),
  ADDRESS_ VARCHAR(40)
);

INSERT INTO TEMPTABLE(TEMPTABLE_NAME, ADDRESS_)
SELECT C_NAME,ADDRESS
FROM CUSTOMERS WHERE ADDRESS= 'Dhaka';

SELECT * FROM TEMPTABLE;

SELECT C.CUST_ID, C.C_NAME
FROM CUSTOMERS C
WHERE C.CUST_ID IN (SELECT B.CUST_ID
FROM BILL B, TRANSACTIONS T
WHERE B.BILL_ID = T.BILL_ID
AND T.PAYABLE = 'PROCESSED');

--UNION ALL OPERATION
SELECT CUST_ID, C_NAME
FROM CUSTOMERS
WHERE ADDRESS = 'Jamia nagar'
UNION ALL
SELECT C.CUST_ID, C.C_NAME
FROM CUSTOMERS C
WHERE C.CUST_ID IN (SELECT B.CUST_ID
FROM BILL B, TRANSACTIONS T
WHERE B.BILL_ID = T.BILL_ID
AND T.PAYABLE = 'PROCESSED');

--UNION
SELECT CUST_ID, C_NAME
FROM CUSTOMERS
WHERE ADDRESS = 'Jamia nagar'
UNION
SELECT C.CUST_ID, C.C_NAME
FROM CUSTOMERS C
WHERE C.CUST_ID IN (SELECT B.CUST_ID
FROM BILL B, TRANSACTIONS T
WHERE B.BILL_ID = T.BILL_ID
AND T.PAYABLE = 'PROCESSED');

--INTERSECT
SELECT CUST_ID, C_NAME
FROM CUSTOMERS
WHERE ADDRESS = 'Jamia nagar'
INTERSECT
SELECT C.CUST_ID, C.C_NAME
FROM CUSTOMERS C
WHERE C.CUST_ID IN (SELECT B.CUST_ID
FROM BILL B, TRANSACTIONS T
WHERE B.BILL_ID = T.BILL_ID
AND T.PAYABLE = 'PROCESSED');

--MINUS
SELECT CUST_ID, C_NAME
FROM CUSTOMERS
WHERE ADDRESS = 'Ghaziabad'
MINUS
SELECT C.CUST_ID, C.C_NAME
FROM CUSTOMERS C
WHERE C.CUST_ID IN (SELECT B.CUST_ID
FROM BILL B, TRANSACTIONS T
WHERE B.BILL_ID = T.BILL_ID
AND T.PAYABLE = 'PROCESSED');

--precedence of set operators
--without parentheses
SELECT CUST_ID, C_NAME
FROM CUSTOMERS
WHERE ADDRESS = 'Jamia nagar'
UNION
SELECT C.CUST_ID, C.C_NAME
FROM CUSTOMERS C
WHERE C.CUST_ID IN (SELECT B.CUST_ID
FROM BILL B, TRANSACTIONS T
WHERE B.BILL_ID = T.BILL_ID
AND T.PAYABLE = 'PROCESSED')
INTERSECT
SELECT CUST_ID, C_NAME
FROM CUSTOMERS
WHERE ADDRESS = 'Dhaka';

--with parentheses
SELECT CUST_ID, C_NAME
FROM CUSTOMERS
WHERE ADDRESS = 'Jamia nagar'
UNION
(
SELECT C.CUST_ID, C.C_NAME
FROM CUSTOMERS C
WHERE C.CUST_ID IN (SELECT B.CUST_ID
FROM BILL B, TRANSACTIONS T
WHERE B.BILL_ID = T.BILL_ID
AND T.PAYABLE = 'PROCESSED')
INTERSECT
SELECT CUST_ID, C_NAME
FROM CUSTOMERS
WHERE ADDRESS = 'Jamia'
);