-- create view of Complaint table
CREATE VIEW COMPLAINT_DETAILS AS
SELECT
    COM_ID,
    CUST_ID,
    COM,
    STAT
FROM
    COMPLAINT
WHERE STAT LIKE '%PROCESSED%';

SELECT * FROM COMPLAINT_DETAILS;

--inserting into view
Insert into COMPLAINT_DETAILS values(16,1,'COMPLAINT NOT CHECKED','PROCESSED');
-- deleting FROM view
DELETE FROM COMPLAINT_DETAILS WHERE CUST_ID=1;
SELECT * FROM COMPLAINT_DETAILS;
DROP VIEW COMPLAINT_DETAILS;


-- create view using join 
CREATE VIEW CUSTOMERS_BILL AS
SELECT
    CUST_ID,
    C_NAME,
    AMOUNT
FROM
    CUSTOMERS
JOIN BILL USING (CUST_ID);

SELECT * FROM CUSTOMERS_BILL;

--UPDATING VIEW
UPDATE CUSTOMERS_BILL 
SET 
    AMOUNT = 1200
WHERE
    CUST_ID = 10;

SELECT * FROM CUSTOMERS_BILL;
DROP VIEW CUSTOMERS_BILL;
